### ISSUE TITLE
Bug in rendering doc for lexbor

### ISSUE THREAD

**Issue by Vici37** [nobodywasishere/crystaldoc.info#12]
Hello! Thanks for creating and hosting this fantastic tool :D

I found a page in the lexbor documentation that seems to be rendering incorrectly.

Page: https://crystaldoc.info/github/kostya/lexbor/v3.1.2/Lexbor/Node.html

What I see:
![image](https://github.com/nobodywasishere/crystaldoc.info/assets/1459505/67d0eb3b-75f8-4160-8795-027a662182a8)

I'm not seeing any missing css or failed network calls, so not sure what the culprit is.

**Comment by nobodywasishere** [comment]
Hey! Thank you for reaching out. This bug os known about, and if you switch to the latest nightly version of lexbor it should work. There's a fix for it in the compiler itself here, but I'm not sure when it will be merged

https://github.com/crystal-lang/crystal/pull/13786

**Comment by Vici37** [comment]
Aha! So it is :) Thanks for pointing out the master branch version @nobodywasishere! Since it seems there's already a fix, I'll close this Issue.
